components:
  schemas:
    response:
      description: ""
      properties:
        args:
          properties: {}
          type: object
        headers:
          properties:
            Accept:
              minLength: 1
              type: string
            Accept-Encoding:
              minLength: 1
              type: string
            Accept-Language:
              minLength: 1
              type: string
            Host:
              minLength: 1
              type: string
            Upgrade-Insecure-Requests:
              minLength: 1
              type: string
            User-Agent:
              minLength: 1
              type: string
            X-Amzn-Trace-Id:
              minLength: 1
              type: string
          required:
          - Accept
          - Accept-Encoding
          - Accept-Language
          - Host
          - Upgrade-Insecure-Requests
          - User-Agent
          - X-Amzn-Trace-Id
          type: object
        origin:
          minLength: 1
          type: string
        url:
          minLength: 1
          type: string
      required:
      - args
      - headers
      - origin
      - url
      type: object
  securitySchemes:
    default:
      description: ""
      flows:
        implicit:
          authorizationUrl: https://localhost:8243/token
          scopes:
            resource:reader: Internal/reader
          x-scopes-bindings:
            resource:reader: Internal/reader
        password:
          scopes:
            resource:reader: resource:reader
          tokenUrl: https://localhost:8243/token
      type: oauth2
info:
  contact:
    email: prabago@minsait.com
    name: prabago
    url: http://www.atc.com
  description: |
    This is a RESTFul API for demo.
  title: api-tool-httpbin
  version: v3
openapi: 3.0.1
paths:
  /delay/{delay}:
    get:
      description: get delay timer
      operationId: getDelay
      parameters:
      - explode: false
        in: path
        name: delay
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                "200":
                  value:
                    args: {}
                    headers:
                      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                      Accept-Encoding: gzip, deflate, br
                      Accept-Language: es-ES,en;q=0.8,es;q=0.5,en-US;q=0.3
                      Host: eu.httpbin.org
                      Upgrade-Insecure-Requests: "1"
                      User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0)
                        Gecko/20100101 Firefox/82.0
                      X-Amzn-Trace-Id: Root=1-5f9329e9-0954dd7d7573930171b442db
                    origin: 88.8.178.214
                    url: https://eu.httpbin.org/delay
              schema:
                $ref: '#/components/schemas/response'
          description: OK
      security:
      - default:
        - resource:reader
      tags:
      - delay
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /get:
    get:
      description: example Get
      operationId: getGet
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples:
                "200":
                  value:
                    args: {}
                    headers:
                      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                      Accept-Encoding: gzip, deflate, br
                      Accept-Language: es-ES,en;q=0.8,es;q=0.5,en-US;q=0.3
                      Host: eu.httpbin.org
                      Upgrade-Insecure-Requests: "1"
                      User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0)
                        Gecko/20100101 Firefox/82.0
                      X-Amzn-Trace-Id: Root=1-5f9329e9-0954dd7d7573930171b442db
                    origin: 88.8.178.214
                    url: https://eu.httpbin.org/get
              schema:
                $ref: '#/components/schemas/response'
          description: ok
      security:
      - default:
        - resource:reader
      tags:
      - get
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /put:
    put:
      description: Put Operation
      operationId: put-put
      responses:
        "200":
          content:
            application/json:
              examples:
                "200":
                  value:
                    args: {}
                    data: ""
                    files: {}
                    form: {}
                    headers:
                      Accept: application/json
                      Accept-Encoding: gzip, deflate, br
                      Accept-Language: es-ES,en;q=0.8,es;q=0.5,en-US;q=0.3
                      Content-Length: "0"
                      Host: httpbin.org
                      Origin: https://httpbin.org
                      Referer: https://httpbin.org/
                      User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0)
                        Gecko/20100101 Firefox/82.0
                      X-Amzn-Trace-Id: Root=1-5f985491-4abedfb27f6436d159d73789
                    json: null
                    origin: 88.15.50.177
                    url: https://httpbin.org/put
              schema:
                $ref: '#/components/schemas/response'
          description: OK
      summary: ""
security:
- default: []
servers:
- url: https://localhost:8243/httpbin/v2
tags:
- name: delay
- name: get
x-wso2-auth-header: Authorization
x-wso2-basePath: /httpbin/v2
x-wso2-cors:
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
  - authorization
  - Access-Control-Allow-Origin
  - Content-Type
  - SOAPAction
  - apikey
  - testKey
  accessControlAllowMethods:
  - GET
  - PUT
  - POST
  - DELETE
  - PATCH
  - OPTIONS
  accessControlAllowOrigins:
  - '*'
  corsConfigurationEnabled: false
x-wso2-production-endpoints:
  type: http
  urls:
  - https://eu.httpbin.org
x-wso2-response-cache:
  cacheTimeoutInSeconds: 300
  enabled: false
x-wso2-sandbox-endpoints:
  type: http
  urls:
  - http://localhost:4010
x-wso2-transports:
- http
- https
