openapi: 3.0.1
info:
  title: api-tool-httpbin
  version: v2
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /delay/{delay}:
    get:
      parameters:
       -
        name: delay
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - resource:reader
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
  /get:
    get:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default:
         - resource:reader
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes:
            resource:reader: Internal/reader
          x-scopes-bindings:
            resource:reader: Internal/reader
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - https://eu.httpbin.org
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://localhost:32768
  type: http
x-wso2-basePath: /httpbin/v2
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
